### ISSUE TITLE
npm install documentation seems to be wrong

### ISSUE THREAD

**Issue by rathwell** [felixrieseberg/ember-cli-azure-deploy#1]
Seems like the installation command is wrong in all of the documentation.  On the ember-cli documentation site, in the readme of this repository, and npm package documentation for this package, the install command is listed as:

npm install --save-dev -g ember-cli-deploy-azure
azure-deploy init

When trying to install that package, I get:

ember-cli-deploy-azure is not in the npm registry

However, when I use the following, it installs (azure and deploy swapped):

npm install --save-dev -g ember-cli-azure-deploy

**Comment by felixrieseberg** [comment]
_facepalm_. Thanks Mark, I'll fix this across the board.
