### ISSUE TITLE
Failed to run deploy with 'permission denied'

### ISSUE THREAD

**Issue by Dzoay** [felixrieseberg/ember-cli-azure-deploy#11]
I have just been experimenting with this addon to find that it kept failing.
Just ran it from a Kudu console to get a better incite into what is happening and have the output below. As you will see a number of the files don't 'tar' with permission denied errors.

What am I missing here?
Jon.

D:\home\site\repository>starter.cmd bash deploy.sh
Copy assets to for build
./
./.bowerrc
tar: ./.deployment
./.bowerrc: Cannot open: Permission denied
tar: ./.editorconfig
./.deployment: Cannot open: Permission denied
tar: ./.ember-cli
./.editorconfig: Cannot open: Permission denied
tar: ./.gitignore
./.ember-cli: Cannot open: Permission denied
./.jshintrc
tar: ./.gitignore: Cannot open: Permission denied
tar: ./.travis.yml
./.jshintrc: Cannot open: Permission denied
tar: ./.watchmanconfig
./.travis.yml: Cannot open: Permission denied
tar: ./app/
./.watchmanconfig: Cannot open: Permission denied
./app/adapters/
./app/adapters/application.js
./app/app.js
./app/components/
./app/components/.gitkeep
./app/components/dz-text-editor.js
./app/components/language-select.js
./app/controllers/
./app/controllers/.gitkeep
./app/controllers/settings.js
./app/helpers/
./app/helpers/.gitkeep
./app/index.html
./app/instance-initializers/
./app/instance-initializers/i18n.js
./app/locales/
./app/locales/en/
./app/locales/en/config.js
./app/locales/en/translations.js
./app/locales/fr/
./app/locales/fr/config.js
./app/locales/fr/translations.js
./app/models/
./app/models/.gitkeep
./app/models/intervention-module-old.js
./app/models/intervention-module.js
./app/models/intervention.js
./app/models/module-template.js
./app/models/module.js
./app/models/objective.js
./app/models/parameters/
./app/models/parameters/accepted-value.js
./app/models/parameters/category-param.js
./app/models/parameters/constant.js
./app/models/parameters/date-param.js
./app/models/parameters/descriptors/
./app/models/parameters/descriptors/derived-descriptor.js
./app/models/parameters/descriptors/descriptor.js
./app/models/parameters/descriptors/list-descriptor.js
./app/models/parameters/descriptors/range-descriptor.js
./app/models/parameters/multichoice-param.js
./app/models/parameters/numeric-param.js
./app/models/parameters/param.js
./app/models/parameters/string-param.js
./app/pods/
./app/pods/components/
./app/pods/components/dz-date/
./app/pods/components/dz-date/component.js
./app/pods/components/dz-date/template.hbs
./app/pods/components/dz-expression/
./app/pods/components/dz-expression/component.js
./app/pods/components/dz-expression/template.hbs
./app/pods/components/dz-language/
./app/pods/components/dz-language/component.js
./app/pods/components/dz-language/template.hbs
./app/pods/components/dz-multi-select/
./app/pods/components/dz-multi-select/component.js
./app/pods/components/dz-multi-select/template.hbs
./app/pods/components/dz-number/
./app/pods/components/dz-number/component.js
./app/pods/components/dz-number/template.hbs
./app/pods/components/dz-parameter-description/
./app/pods/components/dz-parameter-description/component.js
./app/pods/components/dz-parameter-description/template.hbs
./app/pods/components/dz-parameter-list/
./app/pods/components/dz-parameter-list/component.js
./app/pods/components/dz-parameter-list/template.hbs
./app/pods/components/dz-range/
./app/pods/components/dz-range/component.js
./app/pods/components/dz-range/template.hbs
./app/pods/components/dz-select/
./app/pods/components/dz-select/component.js
./app/pods/components/dz-select/template.hbs
./app/pods/components/dz-text/
./app/pods/components/dz-text/component.js
./app/pods/components/dz-text/template.hbs
./app/pods/module/
./app/pods/module/route.js
./app/pods/module/template.hbs
./app/pods/parameter/
./app/pods/parameter/date/
./app/pods/parameter/date/model.js
./app/pods/parameter/expression/
./app/pods/parameter/expression/model.js
./app/pods/parameter/model.js
./app/pods/parameter/multi-select/
./app/pods/parameter/multi-select/model.js
./app/pods/parameter/number/
./app/pods/parameter/number/model.js
./app/pods/parameter/range/
./app/pods/parameter/range/model.js
./app/pods/parameter/select/
./app/pods/parameter/select/model.js
./app/pods/parameter/text/
./app/pods/parameter/text/model.js
./app/pods/parameters/
./app/pods/parameters/controller.js
./app/pods/parameters/parameters.js
./app/pods/parameters/route.js
./app/pods/parameters/template.hbs
./app/pods/settings/
./app/pods/settings/route.js
./app/pods/settings/template.hbs
./app/router.js
./app/routes/
./app/routes/.gitkeep
./app/routes/application.js
./app/routes/index.js
./app/routes/language.js
./app/routes/login.js
./app/routes/module-template.js
./app/routes/module.js
./app/routes/parameters/
./app/routes/parameters/constants.js
./app/routes/parameters.js
./app/styles/
./app/styles/app.scss
./app/styles/_appvariables.scss
./app/templates/
./app/templates/application.hbs
./app/templates/components/
./app/templates/components/.gitkeep
./app/templates/components/dz-calculate.hbs
./app/templates/components/dz-parallax.hbs
./app/templates/components/dz-text-editor.hbs
./app/templates/components/language-select.hbs
./app/templates/components/parameter/
./app/templates/components/parameter/derived-param.hbs
./app/templates/index.hbs
./app/templates/module-template.hbs
./app/templates/module.hbs
./app/templates/parameters/
./app/templates/parameters/constants.hbs
tar: ./app/transforms/
./app/transforms/raw.js
./app/utils/
./app/utils/Calculator.js
./app/views/
./app/views/.gitkeep
./bower.json
./clean.bat
./bower.json: Cannot open: Permission denied
./config/
./config/environment.js
./deploy.sh
./ember-cli-build.js
./package.json
tar: ./clean.bat: Cannot open: Permission denied
tar: ./deploy.sh: Cannot open: Permission denied
tar: ./ember-cli-build.js: Cannot open: Permission denied
./public/
./public/assets/
./public/assets/favicon.ico
./public/assets/woods.jpg
tar: ./package.json: Cannot open: Permission denied
./public/crossdomain.xml
./public/robots.txt
./README.md
tar: ./testem.json
./README.md: Cannot open: Permission denied
tar: ./tests/
./testem.json: Cannot open: Permission denied
./tests/.jshintrc
./tests/helpers/
./tests/helpers/resolver.js
./tests/helpers/start-app.js
./tests/index.html
./tests/integration/
./tests/integration/components/
./tests/integration/components/dz-text-editor-test.js
./tests/integration/components/language-select-test.js
./tests/integration/pods/
./tests/integration/pods/components/
./tests/integration/pods/components/dz-calculated/
./tests/integration/pods/components/dz-calculated/component-test.js
./tests/integration/pods/components/dz-date-picker/
./tests/integration/pods/components/dz-date-picker/component-test.js
./tests/integration/pods/components/dz-input/
./tests/integration/pods/components/dz-input/component-test.js
./tests/integration/pods/components/dz-language/
./tests/integration/pods/components/dz-language/component-test.js
./tests/integration/pods/components/dz-multi/
./tests/integration/pods/components/dz-multi/component-test.js
./tests/integration/pods/components/dz-multi-large/
./tests/integration/pods/components/dz-multi-large/component-test.js
./tests/integration/pods/components/dz-number/
./tests/integration/pods/components/dz-number/component-test.js
./tests/integration/pods/components/dz-parameter-description/
./tests/integration/pods/components/dz-parameter-description/component-test.js
./tests/integration/pods/components/dz-parameter-list/
./tests/integration/pods/components/dz-parameter-list/component-test.js
./tests/integration/pods/components/dz-pretty-expression/
./tests/integration/pods/components/dz-pretty-expression/component-test.js
./tests/integration/pods/components/dz-range/
./tests/integration/pods/components/dz-range/component-test.js
./tests/integration/pods/components/dz-select/
./tests/integration/pods/components/dz-select/component-test.js
./tests/integration/pods/components/dz-text/
./tests/integration/pods/components/dz-text/component-test.js
./tests/test-helper.js
./tests/unit/
./tests/unit/.gitkeep
./tests/unit/adapters/
./tests/unit/adapters/application-test.js
./tests/unit/components/
./tests/unit/components/dz-calculate-test.js
./tests/unit/components/dz-parallax-test.js
./tests/unit/components/parameter/
./tests/unit/components/parameter/derived-param-test.js
./tests/unit/controllers/
./tests/unit/controllers/interventions-test.js
./tests/unit/controllers/parameter-test.js
./tests/unit/controllers/parameters-test.js
./tests/unit/controllers/posts-test.js
./tests/unit/models/
./tests/unit/models/category-param-test.js
./tests/unit/models/intervention-module-test.js
./tests/unit/models/intervention-test.js
./tests/unit/models/module-template-test.js
./tests/unit/models/module-test.js
./tests/unit/models/objective-test.js
./tests/unit/models/parameter/
./tests/unit/models/parameter/accepted-value-test.js
./tests/unit/models/parameter/constant-test.js
./tests/unit/models/parameter/date-param-test.js
./tests/unit/models/parameter/derived-param-test.js
./tests/unit/models/parameter/multichoice-param-test.js
./tests/unit/models/parameter/numeric-param-test.js
./tests/unit/models/parameter-description-test.js
./tests/unit/models/parameter-test.js
./tests/unit/models/parameters/
./tests/unit/models/parameters/constant-test.js
./tests/unit/models/range-test.js
./tests/unit/pods/
./tests/unit/pods/module/
./tests/unit/pods/module/route-test.js
./tests/unit/pods/param-expression/
./tests/unit/pods/param-expression/model-test.js
./tests/unit/pods/param-multi-select/
./tests/unit/pods/param-multi-select/model-test.js
./tests/unit/pods/param-number/
./tests/unit/pods/param-number/model-test.js
./tests/unit/pods/param-number-range/
./tests/unit/pods/param-number-range/model-test.js
./tests/unit/pods/param-select/
./tests/unit/pods/param-select/model-test.js
./tests/unit/pods/parameter/
./tests/unit/pods/parameter/model-test.js
./tests/unit/pods/parameters/
./tests/unit/pods/parameters/controller-test.js
./tests/unit/pods/parameters/route-test.js
./tests/unit/pods/settings/
./tests/unit/pods/settings/route-test.js
./tests/unit/routes/
./tests/unit/routes/index-test.js
./tests/unit/routes/intervention-modules/
./tests/unit/routes/intervention-modules/edit-test.js
./tests/unit/routes/intervention-modules-test.js
tar: ./tests/unit/routes/login-test.js
./tests/unit/routes/module-template-test.js
./tests/unit/routes/module-test.js
./tests/unit/routes/parameters/
./tests/unit/routes/parameters/constants-test.js
./tests/unit/routes/parameters-test.js
./tests/unit/routes/settings-test.js
./tests/unit/transforms/
./tests/unit/transforms/raw-test.js
./tests/unit/utils/
./tests/unit/utils/maths-test.js
./vendor/
./vendor/.gitkeep
./vendor/shims/
./vendor/shims/math.js
An error has occurred during web site deployment.
Failed to create and extract tarball

D:\home\site\repository>.: Cannot utime: Permission denied
tar: Exiting with failure status due to previous errors

**Comment by felixrieseberg** [comment]
Hm, I honestly have no idea - unless you ran out of space or something. Is there anything unique or special about your website? Which size are you running on?

**Comment by Dzoay** [comment]
Thanks for taking the time to respond. I have got to the bottom of it.
It was down to the size I was running (smallest) and my not reading the correct deployment logs that Kudu provides - the most helpful one was the most resent /site/deployment/guid(?) folder.

It has proven this is a great, easy to use tool, so thanks for sharing.
Jon.
