### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by brianbancroft** [felixrieseberg/ember-cli-azure-deploy#24]
Hi there, I'm trying to deploy a basic app to Azure, and it's not going well. My process has been as follows:

1. Create bare-bones ember-cli app
2. Replace intro content with `<h1>hello world</h1>`
3. Run the following command in my app:
```sh
npm install --save-dev -g ember-cli-azure-deploy
azure-deploy init
```
4. Push my code to a [Github Repo](https://github.com/brianbancroft/sample-ember)
5. Create a resource group and portal on Azure
6. Under `Deployment options`, select Github, with my repo
![image](https://user-images.githubusercontent.com/6225122/32249141-4d5bc2d4-be5e-11e7-851d-2e7434e1e793.png)
7. Sync

At the conclusion, I receive an error:
![image](https://user-images.githubusercontent.com/6225122/32249116-366c1cea-be5e-11e7-9331-771708c9adae.png)

Below are the logs. I'm not sure how to get around this. Is this normal and are other people experiencing the same issue?

## Log
```
Command: bash deploy.sh
Copy assets to /tmp/8d520a293647196 for build
./
./.deployment
./.DS_Store
./.editorconfig
./.ember-cli
./.eslintrc.js
./.gitignore
./.travis.yml
./.watchmanconfig
./app/
./app/app.js
./app/components/
./app/components/.gitkeep
deploy.sh: line 99: \nodejs\0.12.6\node.exe: command not found
./app/controllers/
./app/controllers/.gitkeep
./app/helpers/
./app/helpers/.gitkeep
./app/index.html
./app/models/
./app/models/.gitkeep
./app/resolver.js
./app/router.js
./app/routes/
./app/routes/.gitkeep
./app/styles/
./app/styles/app.css
./app/templates/
./app/templates/application.hbs
./app/templates/components/
./app/templates/components/.gitkeep
./assets/
./assets/vendor.js
./assets/vendor.map
./config/
./config/environment.js
./config/targets.js
./crossdomain.xml
./deploy.sh
./ember-cli-build.js
./index.html
./jsconfig.json
./lib/
./package.json
./public/
./public/crossdomain.xml
./public/robots.txt
./README.md
./robots.txt
./testem.js
./tests/
./tests/.eslintrc.js
./tests/helpers/
./tests/helpers/destroy-app.js
./tests/helpers/module-for-acceptance.js
./tests/helpers/resolver.js
./tests/helpers/start-app.js
./tests/index.html
./tests/integration/
./tests/integration/.gitkeep
./tests/test-helper.js
./tests/unit/
./tests/unit/.gitkeep
./vendor/
./vendor/.gitkeep
Switch to the temp directory
Installing ember-cli
An error has occurred during web site deployment.
ember-cli failed
deploy.sh: line 99: \nodejs\0.12.6\node.exe: command not found\n/opt/Kudu/bin/Scripts/starter.sh bash deploy.sh
```

**Comment by brianbancroft** [comment]
Ground connector fault on my end. Closing

**Comment by brianbancroft** [comment]
Correction: I thought it was an issue where I forgot the autogenerated file in the repo in closing this. I confirm that the issue is still there and the log is the same aside the destination location in line 2.

**Comment by shubmittal** [comment]
@brianbancroft  Were you able to resolve the issue? Am running into the same problem.

**Comment by brianbancroft** [comment]
@shubmittal I did, and was not able to resolve. Due to time constraints, I ended up using an alternative approach.

**Comment by karrinflas** [comment]
Same problem here!, could you please explain your approach @brianbancroft please?
