### ISSUE TITLE
Recommended way to ship server

### ISSUE THREAD

**Issue by tp** [felixrieseberg/ember-cli-azure-deploy#4]
Is there a recommended way in your opinion to ship a (node.js) server with this?

Since Ember CLI removed the `api-stub` blueprint and now only ships with `http-mock` (which is not used for production), I think I will stick with shipping a separate API server, unless I am missing something and this would offer a great way to ship client and server in one package.

**Comment by felixrieseberg** [comment]
I'd recommend sticking with a separate API server. It's cleaner and probably all-around better. That being said, if you can think up a good workflow for yourself, you can always crack open deploy.sh and change the workflow!

Or, if you want to try something new and are looking for a Ember-Cli-like backend experience, check out Sails (https://github.com/balderdashy/sails) - people seem to really like it.
