### ISSUE TITLE
Unable to deploy my ember-cli app to azure using this module.

### ISSUE THREAD

**Issue by alexmasita** [felixrieseberg/ember-cli-azure-deploy#5]
Tried to deploy my ember-cli app with this module on a small starter ember app and it worked perfectly and was able to host it but now trying again to deploy a more advanced ember-cli app and it throws this error below in the microsoft azure preview portal: (can you help?)

Failed to set up continuous deployment
Failed to set up continuous deployment for web app VTEmberClient, using Bitbucket. Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<GetSSHKey>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.Hosting.Administration.BitbucketSiteRepositoryProvider.<UpdateSiteSourceControl>d__6.MoveNext().

**Comment by felixrieseberg** [comment]
Hey! While I've seen the deployment thing fail with more sophisticated (read: fat) apps, this seems to be more an Azure issue than an issue with this tool. What's failing in the error you posted is binding the continuous deployment to the repo.

Can you try another deployment method (something simple like FTP or Dropbox) and see how that goes?

**Comment by alexmasita** [comment]
Thanks for your quick response.  As we speak, I am trying to push my code directly to the azure preview web app git repository and through the terminal, I see a different error message.  I appreciate that this is now not your issue to solve but let me provide you with the error message here below, maybe you may be able to give me some pointers as to how to proceed.  My take on the error is that the free basic bizspark plan (I got under the bizspark program) may not have sufficient temp memory to handle building the ember-cli app which now begs the question, how do I increase it?  Thanks again and here below is the error I got in part if you can help:

remote: npm ERR! nospc ENOSPC, write
remote: npm ERR! nospc This is most likely not a problem with npm itself
remote: An error has occurred during web site deployment.
remote: npm ERR! nospc and is related to insufficient space on your system.
remote: npm install failed
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "d:\Program Files (x86)\nodejs\0.10.32\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" "install" "--no-optional" "--no-bin-links"
remote: npm ERR! cwd D:\local\Temp\c377771e-cd55-4353-86b0-e67fa2bb5d53
remote: npm ERR! node -v v0.10.32
remote: npm ERR! npm -v 1.4.28
remote: npm ERR! code ENOSPC
remote: npm ERR! errno 54
remote: npm ERR! Error: Did not get expected byte count.
remote: npm ERR! expect: 29479
remote: npm ERR! actual: 17408
remote: npm ERR!     at decorate (c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\fstream\lib\abstract.js:67:36)
remote: npm ERR!     at FileWriter.Abstract.error (c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\fstream\lib\abstract.js:61:12)
remote: npm ERR!     at FileWriter._finish (c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\fstream\lib\file-writer.js:98:8)
remote: npm ERR!     at WriteStream.<anonymous> (c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\fstream\lib\file-writer.js:54:8)
remote: npm ERR!     at WriteStream.emit (events.js:92:17)
remote: npm ERR!     at evalmachine.<anonymous>:1609:14
remote: npm ERR!     at c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
remote: npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
remote: npm ERR! If you need help, you may report this _entire_ log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     http://github.com/npm/npm/issues
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "d:\Program Files (x86)\nodejs\0.10.32\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" "install" "--no-optional" "--no-bin-links"
remote: npm ERR! cwd D:\local\Temp\c377771e-cd55-4353-86b0-e67fa2bb5d53
remote: npm ERR! node -v v0.10.32
remote: npm ERR! npm -v 1.4.28
remote: npm ERR! path D:\local\Temp\c377771e-cd55-4353-86b0-e67fa2bb5d53\node_modules\ember-cli\node_modules\npm\node_modules\request\node_modules\hawk\node_modules\boom\images\boom.png
remote: npm ERR! fstream_path D:\local\Temp\c377771e-cd55-4353-86b0-e67fa2bb5d53\node_modules\ember-cli\node_modules\npm\node_modules\request\node_modules\hawk\node_modules\boom\images\boom.png
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! fstream_stack FileWriter._finish (c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\fstream\lib\file-writer.js:98:8)
remote: npm ERR! fstream_stack WriteStream.<anonymous> (c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\fstream\lib\file-writer.js:54:8)
remote: npm ERR! fstream_stack WriteStream.emit (events.js:92:17)
remote: npm ERR! fstream_stack evalmachine.<anonymous>:1609:14
remote: npm ERR! fstream_stack c:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
remote: npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
remote: npm ERR! nospc ENOSPC, write
remote: npm ERR! nospc This is most likely not a problem with npm itself
remote: npm ERR! nospc and is related to insufficient space on your system.
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "d:\Program Files (x86)\nodejs\0.10.32\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" "install" "--no-optional" "--no-bin-links"
remote: npm ERR! cwd D:\local\Temp\c377771e-cd55-4353-86b0-e67fa2bb5d53
remote: npm ERR! node -v v0.10.32
remote: npm ERR! npm -v 1.4.28
remote: npm ERR! code ENOSPC
remote: npm ERR! errno 54
remote: npm
remote: 
remote: ......................................................................................fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
To https://alexmasita@vtemberclient.scm.azurewebsites.net:443/VTEmberClient.git
- [new branch]      master -> master

**Comment by alexmasita** [comment]
I delete the Web App in question under the free bizspark plan on to standard s1 plan and this time the deployment process ran to completion but here below I believe is more an error related to your module.  Error in part:

remote: bower qunit#~1.17.1                          install qunit#1.17.1
remote: bower ember-data#1.0.0-beta.16.1             install ember-data#1.0.0-beta.16.1
remote: bower ember#1.11.1                           install ember#1.11.1
remote: bower qunit-notifications#~0.0.6             install qunit-notifications#0.0.6
remote: bower jquery#^1.11.1                         install jquery#1.11.3
remote: bower bootstrap#~3.3.4                       install bootstrap#3.3.4
remote: 
remote: ember-load-initializers#0.1.4 bower_components\ember-load-initializers
remote: +-- ember#1.11.1
remote: Error: Could not find a part of the path 'D:\local\Temp\f980a74f-7e5d-4f2e-98eb-2df724696ab0\dist'.
remote: 
remote: ember-cli-shims#0.0.3 bower_components\ember-cli-shims
remote: +-- ember#1.11.1
remote: 
remote: ember-cli-test-loader#0.1.3 bower_components\ember-cli-test-loader
remote: 
remote: ember-qunit#0.3.1 bower_components\ember-qunit
remote: 
remote: ember-qunit-notifications#0.0.7 bower_components\ember-qunit-notifications
remote: +-- qunit-notifications#0.0.6
remote: 
remote: loader.js#3.2.0 bower_components\loader.js
remote: 
remote: ember-simple-auth#0.8.0-beta.2 bower_components\ember-simple-auth
remote: +-- ember#1.11.1
remote: 
remote: ember-resolver#0.1.15 bower_components\ember-resolver
remote: +-- ember#1.11.1
remote: 
remote: qunit#1.17.1 bower_components\qunit
remote: 
remote: ember-data#1.0.0-beta.16.1 bower_components\ember-data
remote: +-- ember#1.11.1
remote: 
remote: ember#1.11.1 bower_components\ember
remote: +-- jquery#1.11.3
remote: 
remote: qunit-notifications#0.0.6 bower_components\qunit-notifications
remote: 
remote: jquery#1.11.3 bower_components\jquery
remote: 
remote: bootstrap#3.3.4 bower_components\bootstrap
remote: +-- jquery#1.11.3
remote: Build the dist folder
remote: 
remote: Missing npm-shrinkwrap packages: 
remote: Package: glob
remote: Required by: vt / ember-cli / rimraf
remote:   \* Specified: 4.5.3
remote:   \* Installed: (not installed)
remote: 
remote: Run `rm -rf node_modules/ && npm install` to install missing dependencies.
remote: 
remote: Copy web.config to the dist folder
remote: KuduSync.NET from: 'D:\local\Temp\f980a74f-7e5d-4f2e-98eb-2df724696ab0\dist' to: 'D:\home\site\wwwroot'
remote: An error has occurred during web site deployment.
remote: Kudu Sync failed
remote: 
remote: ...........................................................................................................................................Error - Changes committed to remote repository but deployment to website failed.
To https://alexmasita@vtemberclient.scm.azurewebsites.net:443/VTEmberClient.git
- [new branch]      master -> master
  Alexs-MacBook-Air:VTEmberClient alexmasita$

**Comment by alexmasita** [comment]
Issue resolved.  For some reason, creating the npm shrinkwrap file through 'npm install shrinkwrap --dev' was blowing up the deployment.  On deleting this file and re-uploading directly to the azure git repository and even bitbucket now works.  

Thanks a tonne for giving me the initial pointers!
