### ISSUE TITLE
Integrate npm@3

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/ember-cli-azure-deploy#9]
This is currently dependent upon Ember Cli working seamlessly with npm@3, but once that is the case, we'll gain a bunch of benefits.

**Comment by joukevandermaas** [comment]
FYI, I tested our project on NPM 3 with ember cli 13.8, and it does build successfully now. Let me know if there's anything I can try related to azure to see if it would work there.

**Comment by felixrieseberg** [comment]
Thank you very much - just published ember-cli-azure-deploy 1.3.0, which uses npm3.
